let state={user:null,view:'dashboard',data:null,cart:[],products:[]};
const $=s=>document.querySelector(s); const money=n=>`${Number(n||0).toLocaleString('ar-EG')} ${state.data?.settings?.currency||'ل.س'}`;
function toast(message){const t=$('#toast');t.textContent=message;t.className='toast';setTimeout(()=>t.className='',2600)}
function safe(fn){return Promise.resolve().then(fn).catch(e=>toast(e.message||'حدث خطأ'))}
async function boot(){state.data=await window.api.init();renderLogin()}
function renderLogin(){$('#app').innerHTML=`<main class="login"><section class="login-card"><div class="logo">OM</div><h1>سوق أسامة</h1><p class="muted">نظام إدارة الماركت</p><div class="field"><label>المستخدم</label><select id="username"><option value="owner">المالك</option><option value="cashier">أمين الصندوق</option></select></div><div class="field"><label>الرقم السري</label><input id="pin" type="password" inputmode="numeric" maxlength="4" placeholder="أدخل الرقم السري"></div><button class="btn primary" style="width:100%" onclick="doLogin()">تسجيل الدخول</button><p class="muted" style="font-size:12px">المالك: 1234 · أمين الصندوق: 1111</p></section></main>`}
async function doLogin(){await safe(async()=>{state.user=await window.api.login({username:$('#username').value,pin:$('#pin').value});state.data=await window.api.init();state.view=state.user.role==='cashier'?'pos':'dashboard';renderShell()})}
function renderShell(){const nav=[['dashboard','الرئيسية'],['pos','الكاشير'],['sales','المبيعات'],['purchases','المشتريات'],['inventory','المخزون'],['debts','الديون'],['cash','الصندوق'],['reports','التقارير'],['settings','الإعدادات']].filter(x=>state.user.role==='owner'||['pos','sales','inventory'].includes(x[0]));$('#app').innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="logo">OM</div><div><b>سوق أسامة</b><small class="muted">${state.user.name}</small></div></div><nav class="nav">${nav.map(x=>`<button class="${state.view===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav><button class="btn danger" style="margin-top:auto" onclick="renderLogin()">تسجيل الخروج</button></aside><main class="main"><header class="top"><div><h2 id="title" style="margin:0">${nav.find(x=>x[0]===state.view)?.[1]||'الرئيسية'}</h2><small class="muted">${new Date().toLocaleDateString('ar-SA')}</small></div><span class="tag">${state.user.role==='owner'?'مالك':'أمين صندوق'}</span></header><section class="content" id="view"></section></main></div>`;renderView()}
function go(view){state.view=view;renderShell()}
async function renderView(){const v=$('#view');if(state.view==='dashboard')return dashboard(v);if(state.view==='pos')return pos(v);if(state.view==='inventory')return inventory(v);if(state.view==='sales')return sales(v);if(state.view==='purchases')return purchases(v);if(state.view==='debts')return debts(v);if(state.view==='cash')return cash(v);if(state.view==='reports')return reports(v);return settings(v)}
function dashboard(v){const r=state.data.report;v.innerHTML=`<div class="notice">تم تفعيل قاعدة SQLite الدائمة. البيانات محفوظة بعد إغلاق التطبيق وإعادة تشغيل الجهاز.</div><div class="grid">${[['المبيعات',r.sales],['الربح',r.profit],['ديون العملاء',r.customer_debt],['ديون الموردين',r.supplier_debt],['الصندوق',r.cash],['قيمة المخزون',r.inventory_value]].map(x=>`<div class="card kpi"><span class="muted">${x[0]}</span><b>${money(x[1])}</b></div>`).join('')}</div><div class="card" style="margin-top:16px"><h3>إجراءات سريعة</h3><div class="actions"><button class="btn primary" onclick="go('pos')">بيع جديد</button><button class="btn soft" onclick="go('purchases')">فاتورة شراء</button><button class="btn soft" onclick="go('inventory')">إضافة منتج</button><button class="btn soft" onclick="go('reports')">عرض التقارير</button></div></div>`}
async function pos(v){state.products=await window.api.products({});v.innerHTML=`<div class="pos"><section><div class="toolbar"><input id="pq" placeholder="بحث بالاسم أو الباركود" oninput="filterProducts(this.value)"></div><div class="products" id="products">${productCards(state.products)}</div></section><aside class="card cart"><h3>السلة (${state.cart.length})</h3><div id="cart">${cartHtml()}</div></aside></div>`}
function productCards(list){return list.map(p=>`<button class="card product" ${p.quantity<=0?'disabled':''} onclick="addCart(${p.id})"><h4>${p.name}</h4><div class="price">${money(p.sale_price)}</div><small>المتوفر: ${p.quantity}</small></button>`).join('')||'<p class="muted">لا توجد منتجات</p>'}
function filterProducts(q){$('#products').innerHTML=productCards(state.products.filter(p=>p.name.includes(q)||String(p.barcode||'').includes(q)))}
function addCart(id){const p=state.products.find(x=>x.id===id);const row=state.cart.find(x=>x.product_id===id);if(row){if(row.quantity>=p.quantity)return toast('الكمية غير متوفرة');row.quantity++}else state.cart.push({product_id:id,quantity:1,name:p.name,price:p.sale_price});$('#cart').innerHTML=cartHtml()}
function cartHtml(){return state.cart.map((r,i)=>`<div class="cart-row"><span>${r.name}<br><small>${money(r.price*r.quantity)}</small></span><span class="qty"><button onclick="cartQty(${i},-1)">−</button>${r.quantity}<button onclick="cartQty(${i},1)">+</button></span></div>`).join('')+`<hr><b>الإجمالي: ${money(state.cart.reduce((a,r)=>a+r.price*r.quantity,0))}</b><div class="field"><label>طريقة الدفع</label><select id="pay"><option value="cash">نقدي</option><option value="debt">آجل</option></select></div><div class="field"><input id="customer" placeholder="اسم العميل عند البيع الآجل"></div><button class="btn primary" style="width:100%" onclick="completeSale()" ${state.cart.length?'':'disabled'}>إتمام البيع</button>`}
function cartQty(i,d){state.cart[i].quantity+=d;if(state.cart[i].quantity<=0)state.cart.splice(i,1);$('#cart').innerHTML=cartHtml()}
async function completeSale(){await safe(async()=>{const result=await window.api.createSale({items:state.cart,payment_type:$('#pay').value,customer_name:$('#customer').value,discount:0});toast(`تم حفظ الفاتورة #${result.invoice_no}`);state.cart=[];state.data=await window.api.init();await pos($('#view'))})}
async function inventory(v){const list=await window.api.products({});v.innerHTML=`<div class="toolbar"><button class="btn primary" onclick="productModal()">إضافة منتج</button><input placeholder="بحث" oninput="$('#invrows').innerHTML=productRows(list.filter(p=>p.name.includes(this.value)))"></div><div class="card table-wrap"><table class="table"><thead><tr><th>المنتج</th><th>الباركود</th><th>القسم</th><th>شراء</th><th>بيع</th><th>الكمية</th><th></th></tr></thead><tbody id="invrows">${productRows(list)}</tbody></table></div>`}
function productRows(list){return list.map(p=>`<tr><td>${p.name}</td><td>${p.barcode||'—'}</td><td>${p.category_name||'—'}</td><td>${money(p.purchase_price)}</td><td>${money(p.sale_price)}</td><td><span class="tag ${p.quantity<=p.min_quantity?'orange':''}">${p.quantity}</span></td><td><button class="btn danger" onclick="deleteProduct(${p.id})">تعطيل</button></td></tr>`).join('')}
function productModal(){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="card"><div class="modal-head"><h3>منتج جديد</h3><button onclick="this.closest('.modal').remove()">×</button></div><div class="field"><label>اسم المنتج</label><input id="pn"></div><div class="field"><label>الباركود</label><input id="pb"></div><div class="field"><label>سعر الشراء</label><input id="pc" type="number"></div><div class="field"><label>سعر البيع</label><input id="ps" type="number"></div><div class="field"><label>الكمية</label><input id="pqv" type="number"></div><div class="field"><label>حد التنبيه</label><input id="pm" type="number"></div><button class="btn primary" onclick="saveProduct()">حفظ</button></div>`;document.body.append(m)}
async function saveProduct(){await safe(async()=>{await window.api.saveProduct({name:$('#pn').value,barcode:$('#pb').value,purchase_price:$('#pc').value,sale_price:$('#ps').value,quantity:$('#pqv').value,min_quantity:$('#pm').value});document.querySelector('.modal').remove();inventory($('#view'));toast('تم حفظ المنتج')})}
async function deleteProduct(id){if(!confirm('تعطيل المنتج؟'))return;await safe(async()=>{await window.api.deleteProduct({id});inventory($('#view'));toast('تم تعطيل المنتج')})}
async function sales(v){const list=await window.api.sales({limit:200});v.innerHTML=`<div class="card table-wrap"><table class="table"><thead><tr><th>الفاتورة</th><th>التاريخ</th><th>العميل</th><th>الدفع</th><th>الإجمالي</th><th>الحالة</th><th></th></tr></thead><tbody>${list.map(s=>`<tr><td>#${s.invoice_no}</td><td>${new Date(s.created_at).toLocaleString('ar-SA')}</td><td>${s.customer_name||'عميل نقدي'}</td><td>${s.payment_type==='cash'?'نقدي':'آجل'}</td><td>${money(s.total)}</td><td><span class="tag ${s.status==='voided'?'red':''}">${s.status}</span></td><td><button class="btn danger" onclick="returnSale(${s.id})">مرتجع</button></td></tr>`).join('')}</tbody></table></div>`}
async function returnSale(id){const reason=prompt('سبب المرتجع');if(reason===null)return;await safe(async()=>{await window.api.returnSale({sale_id:id,reason,type:'void',items:[]});toast('تم تسجيل المرتجع');sales($('#view'))})}
async function purchases(v){v.innerHTML=`<div class="card"><h3>فاتورة شراء جديدة</h3><p class="muted">تتم إضافة المورد والصنف والكمية داخل معاملة واحدة وتحديث المخزون والدين أو الصندوق تلقائيًا.</p><button class="btn primary" onclick="purchaseModal()">إنشاء فاتورة شراء</button></div>`}
function purchaseModal(){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="card"><div class="modal-head"><h3>فاتورة شراء</h3><button onclick="this.closest('.modal').remove()">×</button></div><div class="field"><label>اسم المورد</label><input id="sup"></div><div class="field"><label>رقم المنتج</label><input id="ppid" type="number"></div><div class="field"><label>الكمية</label><input id="pqty" type="number"></div><div class="field"><label>سعر الوحدة</label><input id="ppu" type="number"></div><div class="field"><label>الدفع</label><select id="ppay"><option value="cash">نقدي</option><option value="debt">آجل</option></select></div><button class="btn primary" onclick="savePurchase()">حفظ فاتورة الشراء</button></div>`;document.body.append(m)}
async function savePurchase(){await safe(async()=>{await window.api.createPurchase({supplier_name:$('#sup').value,payment_type:$('#ppay').value,items:[{product_id:Number($('#ppid').value),quantity:Number($('#pqty').value),unit_price:Number($('#ppu').value)}]});document.querySelector('.modal').remove();state.data=await window.api.init();toast('تم حفظ الشراء وتحديث المخزون')})}
async function debts(v){const list=await window.api.debts({});v.innerHTML=`<div class="card table-wrap"><table class="table"><thead><tr><th>الطرف</th><th>النوع</th><th>الأصل</th><th>المتبقي</th><th></th></tr></thead><tbody>${list.map(d=>`<tr><td>${d.party_name||'—'}</td><td>${d.type==='customer'?'عميل':'مورد'}</td><td>${money(d.original_amount)}</td><td>${money(d.remaining_amount)}</td><td>${d.remaining_amount>0?`<button class="btn soft" onclick="payDebt(${d.id},${d.remaining_amount})">تسجيل دفعة</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
async function payDebt(id,max){const amount=prompt(`المتبقي ${max}`);if(amount===null)return;await safe(async()=>{await window.api.payDebt({debt_id:id,amount:Number(amount)});debts($('#view'));toast('تم تسجيل الدفعة وتحديث الصندوق')})}
async function cash(v){const c=await window.api.cash();v.innerHTML=`<div class="grid"><div class="card kpi"><span>الرصيد الحالي</span><b>${money(c.balance)}</b></div></div><div class="card table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>النوع</th><th>المبلغ</th><th>الوصف</th><th>التاريخ</th></tr></thead><tbody>${c.rows.map(r=>`<tr><td>${r.type}</td><td>${money(r.amount)}</td><td>${r.description||''}</td><td>${new Date(r.created_at).toLocaleString('ar-SA')}</td></tr>`).join('')}</tbody></table></div><button class="btn primary" onclick="expenseModal()">تسجيل مصروف</button>`}
function expenseModal(){const category=prompt('تصنيف المصروف');if(!category)return;const amount=prompt('المبلغ');if(!amount)return;safe(async()=>{await window.api.createExpense({category,amount,description:category});cash($('#view'));toast('تم تسجيل المصروف')})}
async function reports(v){const r=await window.api.report({});v.innerHTML=`<div class="grid">${[['المبيعات',r.sales],['المشتريات',r.purchases],['الربح',r.profit],['الصندوق',r.cash],['المخزون',r.inventory_value],['ديون العملاء',r.customer_debt],['ديون الموردين',r.supplier_debt]].map(x=>`<div class="card kpi"><span>${x[0]}</span><b>${money(x[1])}</b></div>`).join('')}</div>`}
async function settings(v){v.innerHTML=`<div class="card"><h3>الإعدادات والنسخ الاحتياطي</h3><div class="field"><label>اسم المتجر</label><input id="storeName" value="${state.data.settings.store_name}"></div><div class="field"><label>العملة</label><input id="currency" value="${state.data.settings.currency}"></div><div class="actions"><button class="btn primary" onclick="saveSettings()">حفظ</button><button class="btn soft" onclick="window.api.exportBackup().then(()=>toast('تم تصدير النسخة الاحتياطية'))">تصدير قاعدة البيانات</button><button class="btn danger" onclick="window.api.importBackup().then(()=>location.reload())">استعادة قاعدة البيانات</button></div></div>`}
async function saveSettings(){await safe(async()=>{await window.api.saveSettings({store_name:$('#storeName').value,currency:$('#currency').value});state.data=await window.api.init();toast('تم حفظ الإعدادات')})}
boot().catch(e=>toast(e.message));
